import { db } from "../db";
import { publicProcedure } from "../trpc/context";

export const listAddresses = publicProcedure.query(async () => {
  const addresses = await db.query.addresses.findMany();
  console.log(addresses);

  return [
    {
      id: 1,
      street: "123 Main St",
      city: "New York",
      state: "NY",
      postalCode: "10001",
      country: "United States",
    },
    {
      id: 2,
      street: "1 Infinite Loop",
      city: "Cupertino",
      state: "CA",
      postalCode: "95014",
      country: "United States",
    },
    {
      id: 3,
      street: "221B Baker St",
      city: "London",
      state: "",
      postalCode: "NW1 6XE",
      country: "United Kingdom",
    },
    {
      id: 4,
      street: "Champs-Élysées",
      city: "Paris",
      state: "",
      postalCode: "75008",
      country: "France",
    },
    {
      id: 5,
      street: "Alexanderplatz 1",
      city: "Berlin",
      state: "",
      postalCode: "10178",
      country: "Germany",
    },
    {
      id: 6,
      street: "Shibuya Crossing",
      city: "Tokyo",
      state: "",
      postalCode: "150-0043",
      country: "Japan",
    },
    {
      id: 7,
      street: "Bondi Beach",
      city: "Sydney",
      state: "NSW",
      postalCode: "2026",
      country: "Australia",
    },
    {
      id: 8,
      street: "Copacabana Beach",
      city: "Rio de Janeiro",
      state: "",
      postalCode: "22070-011",
      country: "Brazil",
    },
    {
      id: 9,
      street: "Taj Mahal Palace",
      city: "Mumbai",
      state: "Maharashtra",
      postalCode: "400001",
      country: "India",
    },
    {
      id: 10,
      street: "CN Tower",
      city: "Toronto",
      state: "ON",
      postalCode: "M5V 2T6",
      country: "Canada",
    },
    {
      id: 11,
      street: "Burj Khalifa",
      city: "Dubai",
      state: "",
      postalCode: "",
      country: "United Arab Emirates",
    },
    {
      id: 12,
      street: "Table Mountain",
      city: "Cape Town",
      state: "",
      postalCode: "8001",
      country: "South Africa",
    },
    {
      id: 13,
      street: "Red Square",
      city: "Moscow",
      state: "",
      postalCode: "109012",
      country: "Russia",
    },
    {
      id: 14,
      street: "Great Wall",
      city: "Beijing",
      state: "",
      postalCode: "100000",
      country: "China",
    },
    {
      id: 15,
      street: "Machu Picchu",
      city: "Cusco",
      state: "",
      postalCode: "",
      country: "Peru",
    },
    {
      id: 16,
      street: "Acropolis",
      city: "Athens",
      state: "",
      postalCode: "10558",
      country: "Greece",
    },
    {
      id: 17,
      street: "Colosseum",
      city: "Rome",
      state: "",
      postalCode: "00184",
      country: "Italy",
    },
    {
      id: 18,
      street: "Sagrada Familia",
      city: "Barcelona",
      state: "",
      postalCode: "08013",
      country: "Spain",
    },
    {
      id: 19,
      street: "Pyramids of Giza",
      city: "Cairo",
      state: "",
      postalCode: "",
      country: "Egypt",
    },
    {
      id: 20,
      street: "Petronas Towers",
      city: "Kuala Lumpur",
      state: "",
      postalCode: "50088",
      country: "Malaysia",
    },
    {
      id: 21,
      street: "456 Park Ave",
      city: "Chicago",
      state: "IL",
      postalCode: "60601",
      country: "United States",
    },
    {
      id: 22,
      street: "789 Ocean Blvd",
      city: "Miami",
      state: "FL",
      postalCode: "33139",
      country: "United States",
    },
    {
      id: 23,
      street: "101 Pine St",
      city: "San Francisco",
      state: "CA",
      postalCode: "94111",
      country: "United States",
    },
    {
      id: 24,
      street: "202 Maple Ave",
      city: "Boston",
      state: "MA",
      postalCode: "02108",
      country: "United States",
    },
    {
      id: 25,
      street: "303 Oak Dr",
      city: "Seattle",
      state: "WA",
      postalCode: "98101",
      country: "United States",
    },
  ];
});
